#!/usr/bin/env python3
"""Synthetic checkpoint fixture generator for SynapseFS.

Why this tool exists
--------------------
SynapseFS is graded on *permutation-recovery accuracy* against checkpoint pairs
the team has never seen. There is exactly one way to measure that: apply a
permutation ourselves, withhold it from the alignment engine, and check whether
the engine reproduces it. That answer key cannot come from real checkpoints —
it has to be manufactured. This tool manufactures it.

The problem statement also asks that large synthetic fixtures stay out of commit
history and be regenerated by script instead; this is that script.

What it emits
-------------
For each model spec, five variants are written, each a directory containing
``model.safetensors`` + ``config.json``:

===================== ================================ ==========================
Variant               Construction                     Exercises
===================== ================================ ==========================
``base``              random init                      root-commit / full storage
``permuted``          ``base`` with a known pi applied  permutation recovery
``finetuned``         ``base`` + small dense noise      residual ratio
``permuted_finetuned``both of the above                 the hard case
``not_alignable``     independent random init          explicit non-alignability
===================== ================================ ==========================

``permuted`` and ``permuted_finetuned`` additionally carry ``ground_truth.json``
holding the permutations that were applied.

**The alignment engine must never read ``ground_truth.json``.** It is written for
tests and scoring only. If production code reads it, the accuracy metric becomes
meaningless. ``config.json`` is the only metadata the aligner is entitled to see,
and it is deliberately shaped like an ordinary HuggingFace config rather than
like a convenient description of our own internals.

Self-verification
-----------------
Applying a permutation correctly is itself fiddly: a row permutation on layer
``l`` must be matched by a column permutation on layer ``l+1``, biases and
normalisation parameters follow the row permutation, residual connections force
two layers to *share* a permutation group, and a conv-to-linear flatten permutes
*blocks* of columns rather than individual columns. Get any of that wrong and the
generator emits a model that is not functionally equivalent to its base — at
which point the aligner faithfully recovers nonsense and every test still passes.

So the generator checks itself: it pushes a fixed random input through the base
and through the permuted model and asserts the outputs match (§ :func:`verify_equivalence`).
That check doubles as a free correctness test of the exact permutation algebra
Track B has to reimplement.

Usage
-----
::

    python tools/gen_fixtures.py --arch mlp --size tiny  --out fixtures/mlp-tiny
    python tools/gen_fixtures.py --arch cnn --size small --out fixtures/cnn-small
    python tools/gen_fixtures.py --all --size tiny --out fixtures/
    python tools/gen_fixtures.py --arch mlp --size small --variants base finetuned
"""

from __future__ import annotations

import argparse
import json
import math
import os
import shutil
import struct
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Iterable

import numpy as np

# --------------------------------------------------------------------------- #
# Types
# --------------------------------------------------------------------------- #

# A model is a flat name -> array mapping, mirroring the .safetensors key/value
# shape. Arrays are float32 while we are building and permuting them; they are
# narrowed to the storage dtype only at write time (see `to_storage_dtype`).
Tensors = dict[str, np.ndarray]

# A permutation group maps a group id (e.g. "g_hidden_0") to an int32 array `p`
# where `p[i]` is the index in the *source* model that lands at position `i` in
# the *permuted* model. This matches the `base_row_permutation` convention in
# docs/FileFormat.md section 4.2, deliberately: fixtures and production speak the
# same dialect.
PermGroups = dict[str, np.ndarray]

ALL_VARIANTS = (
    "base",
    "permuted",
    "finetuned",
    "permuted_finetuned",
    "not_alignable",
)


# --------------------------------------------------------------------------- #
# safetensors writer
# --------------------------------------------------------------------------- #
#
# We write .safetensors by hand rather than via safetensors.numpy.save_file for
# two reasons:
#
#   1. bf16 has no numpy dtype, so the numpy backend cannot emit it, and the PS
#      says checkpoints are evaluated in fp16/bf16. Writing the container
#      ourselves gets bf16 for free -- the payload is just uint16 bytes.
#   2. It forces us to encode the three conventions that silently break
#      byte-exactness downstream (see docs/FileFormat.md section 1.2), so they
#      are exercised from day one rather than discovered during integration.
#
# tests/test_fixtures.py asserts this writer round-trips through the real
# safetensors reader, which is what makes the shortcut safe.

_DTYPE_TO_ST: dict[str, str] = {
    "float16": "F16",
    "bfloat16": "BF16",
    "float32": "F32",
    "float64": "F64",
    "int64": "I64",
    "int32": "I32",
    "uint8": "U8",
    "bool": "BOOL",
}


def _st_dtype_name(arr: np.ndarray, declared: str | None) -> str:
    """Return the safetensors dtype string for `arr`.

    `declared` overrides inference and exists solely for bf16, which is carried
    in memory as uint16 because numpy has no bfloat16 dtype.
    """
    if declared is not None:
        return declared
    name = arr.dtype.name
    if name not in _DTYPE_TO_ST:
        raise ValueError(f"unsupported dtype for safetensors: {name}")
    return _DTYPE_TO_ST[name]


def save_safetensors(
    path: Path,
    tensors: Tensors,
    metadata: dict[str, str] | None = None,
    dtype_overrides: dict[str, str] | None = None,
) -> None:
    """Write `tensors` to `path` in .safetensors format.

    Reproduces the three layout conventions that a naive re-serialisation gets
    wrong, all verified against a file produced by safetensors 0.8.0:

    1. ``__metadata__`` is emitted first, before any tensor key.
    2. Tensor keys are sorted **alphabetically**, not by insertion order, and
       ``data_offsets`` follow that sorted order.
    3. The header JSON is padded with trailing spaces (0x20) so that
       ``8 + header_len`` is a multiple of 8, aligning the data region for mmap.

    Args:
        path: Destination file. Parent directories must already exist.
        tensors: Name -> array. Arrays must be C-contiguous.
        metadata: Optional string->string map stored under ``__metadata__``.
        dtype_overrides: Name -> safetensors dtype string, used to declare BF16
            for arrays carried as uint16.
    """
    dtype_overrides = dtype_overrides or {}
    header: dict[str, Any] = {}
    if metadata:
        header["__metadata__"] = {str(k): str(v) for k, v in metadata.items()}

    # Offsets are assigned in sorted-key order because that is the order the
    # payload is concatenated in below.
    offset = 0
    ordered: list[tuple[str, np.ndarray]] = []
    for name in sorted(tensors):
        arr = np.ascontiguousarray(tensors[name])
        nbytes = arr.nbytes
        header[name] = {
            "dtype": _st_dtype_name(arr, dtype_overrides.get(name)),
            "shape": list(arr.shape),
            "data_offsets": [offset, offset + nbytes],
        }
        ordered.append((name, arr))
        offset += nbytes

    blob = json.dumps(header, separators=(",", ":")).encode("utf-8")
    pad = (-(8 + len(blob))) % 8          # pad so the data region is 8-aligned
    blob += b" " * pad

    with open(path, "wb") as fh:
        fh.write(struct.pack("<Q", len(blob)))
        fh.write(blob)
        for _, arr in ordered:
            fh.write(arr.tobytes(order="C"))


def to_storage_dtype(arr: np.ndarray, dtype: str) -> tuple[np.ndarray, str | None]:
    """Narrow a float32 working array to the on-disk storage dtype.

    Returns:
        ``(array, declared_dtype)``. For bf16 the array is uint16 and
        `declared_dtype` is ``"BF16"``, because numpy cannot represent bf16 and
        safetensors must be told explicitly. For every other dtype
        `declared_dtype` is None and inference handles it.

    Note:
        bf16 conversion truncates rather than rounding to nearest even. That is
        fine for fixtures -- we only need *some* valid bf16 bit pattern, not the
        nearest one -- and it keeps the conversion a pure bit operation.
    """
    if dtype == "bf16":
        u32 = np.ascontiguousarray(arr, dtype=np.float32).view(np.uint32)
        return (u32 >> 16).astype(np.uint16), "BF16"
    if dtype == "fp16":
        return arr.astype(np.float16), None
    if dtype == "fp32":
        return arr.astype(np.float32), None
    raise ValueError(f"unknown storage dtype: {dtype!r}")


# --------------------------------------------------------------------------- #
# Model specs
# --------------------------------------------------------------------------- #


@dataclass(frozen=True)
class MLPSpec:
    """A plain feed-forward stack: Linear -> LayerNorm -> ReLU, repeated.

    Attributes:
        in_dim: Input feature count. Pinned -- never permuted.
        hidden: Width of every hidden layer.
        depth: Number of Linear layers *including* the output layer, so there
            are ``depth - 1`` permutable groups.
        out_dim: Output feature count. Pinned -- never permuted.
    """

    in_dim: int
    hidden: int
    depth: int
    out_dim: int

    @property
    def param_count(self) -> int:
        """Approximate parameter count, for size reporting."""
        n = self.in_dim * self.hidden + self.hidden
        n += (self.depth - 2) * (self.hidden * self.hidden + self.hidden)
        n += self.hidden * self.out_dim + self.out_dim
        n += (self.depth - 1) * 2 * self.hidden          # LayerNorm affine
        return n


@dataclass(frozen=True)
class CNNSpec:
    """A ResNet-style stack: stem conv, N residual basic blocks, linear head.

    Channel width is constant throughout and there is no downsampling. That is
    deliberate: it keeps every residual skip an identity, which forces the block
    input and block output to *share* a permutation group. Group tying is the
    part of the topology resolver most likely to be wrong, so the fixtures
    should exercise it.

    Attributes:
        in_ch: Input image channels. Pinned.
        channels: Constant channel width for the stem and every block.
        blocks: Number of residual basic blocks.
        spatial: Input height and width (square).
        num_classes: Head output width. Pinned.
        head: ``"flatten"`` or ``"pool"``. ``"flatten"`` makes the head's input
            ``channels * spatial * spatial``, so a channel permutation moves
            *blocks* of ``spatial**2`` columns -- the conv-to-linear flatten
            case. ``"pool"`` global-average-pools first, giving block size 1.
            Default is ``"flatten"`` precisely because it is the harder path.
    """

    in_ch: int
    channels: int
    blocks: int
    spatial: int
    num_classes: int
    head: str = "flatten"

    @property
    def block_size(self) -> int:
        """Columns per channel in the head weight -- the `col_block_size`."""
        return self.spatial * self.spatial if self.head == "flatten" else 1

    @property
    def param_count(self) -> int:
        """Approximate parameter count, for size reporting."""
        c = self.channels
        n = c * self.in_ch * 9 + 4 * c
        n += self.blocks * (2 * c * c * 9 + 8 * c)
        n += self.num_classes * c * self.block_size + self.num_classes
        return n


SIZE_PRESETS: dict[str, dict[str, Any]] = {
    "tiny": {
        "mlp": MLPSpec(in_dim=64, hidden=256, depth=4, out_dim=10),
        "cnn": CNNSpec(in_ch=3, channels=32, blocks=2, spatial=8, num_classes=10),
    },
    "small": {
        "mlp": MLPSpec(in_dim=256, hidden=1024, depth=8, out_dim=100),
        "cnn": CNNSpec(in_ch=3, channels=64, blocks=4, spatial=8, num_classes=100),
    },
    "medium": {
        "mlp": MLPSpec(in_dim=512, hidden=2048, depth=16, out_dim=1000),
        "cnn": CNNSpec(in_ch=3, channels=128, blocks=6, spatial=8, num_classes=1000),
    },
    "large": {
        "mlp": MLPSpec(in_dim=1024, hidden=4096, depth=24, out_dim=1000),
        "cnn": CNNSpec(in_ch=3, channels=256, blocks=8, spatial=8, num_classes=1000),
    },
}


# --------------------------------------------------------------------------- #
# Model construction
# --------------------------------------------------------------------------- #


def _kaiming(rng: np.random.Generator, *shape: int, fan_in: int) -> np.ndarray:
    """He-normal init. Realistic magnitudes matter for the residual-ratio metric."""
    return rng.normal(0.0, math.sqrt(2.0 / fan_in), size=shape).astype(np.float32)


def build_mlp(spec: MLPSpec, rng: np.random.Generator) -> Tensors:
    """Construct a randomly initialised MLP.

    Tensor naming mirrors a typical PyTorch ``state_dict`` so the topology
    parser is exercised against realistic key strings rather than a convenient
    private scheme.
    """
    t: Tensors = {}
    dims = [spec.in_dim] + [spec.hidden] * (spec.depth - 1) + [spec.out_dim]
    for i in range(spec.depth):
        fan_in, fan_out = dims[i], dims[i + 1]
        t[f"layers.{i}.weight"] = _kaiming(rng, fan_out, fan_in, fan_in=fan_in)
        t[f"layers.{i}.bias"] = np.zeros(fan_out, dtype=np.float32)
        if i < spec.depth - 1:                       # no norm on the output layer
            t[f"layers.{i}.norm.weight"] = np.ones(fan_out, dtype=np.float32)
            t[f"layers.{i}.norm.bias"] = np.zeros(fan_out, dtype=np.float32)
    return t


def build_cnn(spec: CNNSpec, rng: np.random.Generator) -> Tensors:
    """Construct a randomly initialised ResNet-style CNN.

    BatchNorm running statistics are randomised rather than left at their
    ``(0, 1)`` defaults. If they stayed at defaults they would be identical
    across every variant and would dedup perfectly, quietly flattering the
    residual-ratio metric.
    """
    t: Tensors = {}
    c = spec.channels

    t["stem.weight"] = _kaiming(rng, c, spec.in_ch, 3, 3, fan_in=spec.in_ch * 9)
    _add_bn(t, "stem.bn", c, rng)

    for b in range(spec.blocks):
        t[f"blocks.{b}.conv1.weight"] = _kaiming(rng, c, c, 3, 3, fan_in=c * 9)
        _add_bn(t, f"blocks.{b}.bn1", c, rng)
        t[f"blocks.{b}.conv2.weight"] = _kaiming(rng, c, c, 3, 3, fan_in=c * 9)
        _add_bn(t, f"blocks.{b}.bn2", c, rng)

    head_in = c * spec.block_size
    t["head.weight"] = _kaiming(rng, spec.num_classes, head_in, fan_in=head_in)
    t["head.bias"] = np.zeros(spec.num_classes, dtype=np.float32)
    return t


def _add_bn(t: Tensors, prefix: str, c: int, rng: np.random.Generator) -> None:
    """Add the four BatchNorm tensors under `prefix`, all on the channel axis."""
    t[f"{prefix}.weight"] = rng.uniform(0.8, 1.2, size=c).astype(np.float32)
    t[f"{prefix}.bias"] = rng.normal(0.0, 0.05, size=c).astype(np.float32)
    t[f"{prefix}.running_mean"] = rng.normal(0.0, 0.1, size=c).astype(np.float32)
    t[f"{prefix}.running_var"] = rng.uniform(0.5, 1.5, size=c).astype(np.float32)


# --------------------------------------------------------------------------- #
# Permutation
# --------------------------------------------------------------------------- #


def _permute_rows(w: np.ndarray, p: np.ndarray) -> np.ndarray:
    """Permute axis 0. ``out[i] == w[p[i]]``."""
    return w[p]


def _permute_cols(w: np.ndarray, p: np.ndarray, block: int = 1) -> np.ndarray:
    """Permute axis 1 in contiguous blocks of `block` columns.

    ``block == 1`` is the ordinary linear case. ``block > 1`` is the
    conv-to-linear flatten case: a flattened ``[out, in_ch * H * W]`` weight has
    its columns grouped by input channel, so permuting channel ``c`` to position
    ``i`` moves the whole span ``[c*block, (c+1)*block)``.

    This is the single most error-prone line in the file. It is also invisible
    under an identity permutation, which is why the CNN fixture must be tested
    with a non-identity one.
    """
    if block == 1:
        return w[:, p]
    idx = (p[:, None] * block + np.arange(block)[None, :]).ravel()
    return w[:, idx]


def permute_mlp(spec: MLPSpec, t: Tensors, rng: np.random.Generator) -> tuple[Tensors, PermGroups]:
    """Apply a random permutation to every hidden layer of an MLP.

    The input and output layers are pinned: permuting them would change the
    function the network computes as seen from outside, which is exactly what
    permutation symmetry does *not* do.

    Returns:
        ``(permuted_tensors, groups)`` where `groups` maps ``"g_hidden_{i}"`` to
        the permutation applied to layer ``i``'s output.
    """
    groups: PermGroups = {
        f"g_hidden_{i}": rng.permutation(spec.hidden).astype(np.int32)
        for i in range(spec.depth - 1)
    }
    ident_in = np.arange(spec.in_dim, dtype=np.int32)
    out: Tensors = {}

    for i in range(spec.depth):
        p_in = ident_in if i == 0 else groups[f"g_hidden_{i - 1}"]
        p_out = groups.get(f"g_hidden_{i}")           # None on the output layer

        w = t[f"layers.{i}.weight"]
        w = _permute_cols(w, p_in)
        if p_out is not None:
            w = _permute_rows(w, p_out)
        out[f"layers.{i}.weight"] = w

        b = t[f"layers.{i}.bias"]
        out[f"layers.{i}.bias"] = b if p_out is None else b[p_out]

        if p_out is not None:
            for suf in ("norm.weight", "norm.bias"):
                out[f"layers.{i}.{suf}"] = t[f"layers.{i}.{suf}"][p_out]

    return out, groups


def permute_cnn(spec: CNNSpec, t: Tensors, rng: np.random.Generator) -> tuple[Tensors, PermGroups]:
    """Apply a random permutation to a ResNet-style CNN.

    Two kinds of group, and the distinction is the point of this fixture:

    * ``g_skip`` -- the residual-path width. Because every skip connection is an
      identity, the stem output, every ``conv2`` output, and the head's input
      channels must **all** use the same permutation. A resolver that treats
      each layer independently will produce a model that is not functionally
      equivalent, and :func:`verify_equivalence` will catch it.
    * ``g_block_{b}`` -- block ``b``'s internal width, between ``conv1`` and
      ``conv2``. Free to permute independently.
    """
    groups: PermGroups = {"g_skip": rng.permutation(spec.channels).astype(np.int32)}
    for b in range(spec.blocks):
        groups[f"g_block_{b}"] = rng.permutation(spec.channels).astype(np.int32)

    p_skip = groups["g_skip"]
    ident_in = np.arange(spec.in_ch, dtype=np.int32)
    out: Tensors = {}

    # Stem: rows on the skip group, columns pinned to the input channels.
    out["stem.weight"] = t["stem.weight"][np.ix_(p_skip, ident_in)]
    _permute_bn(out, t, "stem.bn", p_skip)

    for b in range(spec.blocks):
        p_int = groups[f"g_block_{b}"]
        # conv1: rows -> internal group, cols -> skip group (block input).
        out[f"blocks.{b}.conv1.weight"] = t[f"blocks.{b}.conv1.weight"][np.ix_(p_int, p_skip)]
        _permute_bn(out, t, f"blocks.{b}.bn1", p_int)
        # conv2: rows -> skip group (tied to the residual), cols -> internal.
        out[f"blocks.{b}.conv2.weight"] = t[f"blocks.{b}.conv2.weight"][np.ix_(p_skip, p_int)]
        _permute_bn(out, t, f"blocks.{b}.bn2", p_skip)

    # Head: rows pinned (class logits), columns follow the skip group in blocks.
    out["head.weight"] = _permute_cols(t["head.weight"], p_skip, spec.block_size)
    out["head.bias"] = t["head.bias"].copy()
    return out, groups


def _permute_bn(out: Tensors, t: Tensors, prefix: str, p: np.ndarray) -> None:
    """Apply `p` to all four BatchNorm tensors under `prefix`."""
    for suf in ("weight", "bias", "running_mean", "running_var"):
        out[f"{prefix}.{suf}"] = t[f"{prefix}.{suf}"][p]


# --------------------------------------------------------------------------- #
# Perturbation
# --------------------------------------------------------------------------- #


def finetune(t: Tensors, rng: np.random.Generator, rel_scale: float = 1e-3) -> Tensors:
    """Perturb every tensor to imitate a fine-tuning step.

    The noise is scaled *relative to each tensor's own standard deviation*, so a
    weight matrix and a BatchNorm gamma both move by a comparable fraction of
    their natural magnitude. A single absolute scale would leave small-magnitude
    tensors untouched and make the residual look better than it should.

    The perturbation is dense -- every element moves. That is the realistic
    fine-tuning case and it is why chunk-level deduplication buys little on the
    residual itself (see docs/FORMAT.md section 1.3).

    Args:
        rel_scale: Noise standard deviation as a fraction of each tensor's own.
            ``1e-3`` is a light step; raise it to model a longer run.
    """
    out: Tensors = {}
    for k, v in t.items():
        sigma = float(v.std()) or 1.0
        out[k] = (v + rng.normal(0.0, sigma * rel_scale, size=v.shape)).astype(np.float32)
    return out


# --------------------------------------------------------------------------- #
# Forward passes (self-verification only)
# --------------------------------------------------------------------------- #
#
# These exist so the generator can prove it permuted correctly. They are not
# performance-sensitive and are not used by anything in synapsefs/.


def _layernorm(x: np.ndarray, g: np.ndarray, b: np.ndarray, eps: float = 1e-5) -> np.ndarray:
    """LayerNorm over the last axis.

    Permutation-equivariant, which is why permuting a hidden layer is safe:
    mean and variance are taken over *all* features, so reordering them leaves
    both statistics unchanged.
    """
    mu = x.mean(axis=-1, keepdims=True)
    var = x.var(axis=-1, keepdims=True)
    return (x - mu) / np.sqrt(var + eps) * g + b


def forward_mlp(spec: MLPSpec, t: Tensors, x: np.ndarray) -> np.ndarray:
    """Run `x` (shape ``[N, in_dim]``) through the MLP in float32."""
    h = x.astype(np.float32)
    for i in range(spec.depth):
        h = h @ t[f"layers.{i}.weight"].T.astype(np.float32) + t[f"layers.{i}.bias"]
        if i < spec.depth - 1:
            h = _layernorm(h, t[f"layers.{i}.norm.weight"], t[f"layers.{i}.norm.bias"])
            h = np.maximum(h, 0.0)
    return h


def _conv2d(x: np.ndarray, w: np.ndarray, pad: int = 1) -> np.ndarray:
    """Stride-1 2D convolution, NCHW, accumulating one kernel offset at a time."""
    n, _, hh, ww = x.shape
    o, _, kh, kw = w.shape
    xp = np.pad(x, ((0, 0), (0, 0), (pad, pad), (pad, pad)))
    out = np.zeros((n, o, hh, ww), dtype=np.float32)
    for i in range(kh):
        for j in range(kw):
            out += np.einsum("nchw,oc->nohw", xp[:, :, i : i + hh, j : j + ww], w[:, :, i, j])
    return out


def _batchnorm(x: np.ndarray, t: Tensors, prefix: str, eps: float = 1e-5) -> np.ndarray:
    """Inference-mode BatchNorm using the stored running statistics."""
    m = t[f"{prefix}.running_mean"][None, :, None, None]
    v = t[f"{prefix}.running_var"][None, :, None, None]
    g = t[f"{prefix}.weight"][None, :, None, None]
    b = t[f"{prefix}.bias"][None, :, None, None]
    return (x - m) / np.sqrt(v + eps) * g + b


def forward_cnn(spec: CNNSpec, t: Tensors, x: np.ndarray) -> np.ndarray:
    """Run `x` (shape ``[N, in_ch, S, S]``) through the CNN in float32."""
    h = np.maximum(_batchnorm(_conv2d(x, t["stem.weight"]), t, "stem.bn"), 0.0)
    for b in range(spec.blocks):
        r = h
        h = np.maximum(_batchnorm(_conv2d(h, t[f"blocks.{b}.conv1.weight"]), t, f"blocks.{b}.bn1"), 0.0)
        h = _batchnorm(_conv2d(h, t[f"blocks.{b}.conv2.weight"]), t, f"blocks.{b}.bn2")
        h = np.maximum(h + r, 0.0)                    # identity skip -> tied group
    h = h.reshape(h.shape[0], -1) if spec.head == "flatten" else h.mean(axis=(2, 3))
    return h @ t["head.weight"].T + t["head.bias"]


def verify_equivalence(
    forward: Callable[[Tensors, np.ndarray], np.ndarray],
    base: Tensors,
    permuted: Tensors,
    x: np.ndarray,
    tol: float = 1e-3,
) -> float:
    """Assert that permuting did not change the function the network computes.

    This is the load-bearing check in the whole tool. A permutation is only a
    *symmetry* if the model's outputs are unchanged; if they are not, the
    fixture is wrong and every downstream accuracy number computed against it is
    meaningless.

    Args:
        tol: Maximum tolerated relative deviation. Float32 accumulation over a
            deep stack drifts slightly even for an exact permutation, because
            summation order changes -- so this is deliberately not exact
            equality. Byte-exactness is a property of the *storage* layer, not
            of this arithmetic.

    Returns:
        The observed maximum relative deviation, for reporting.

    Raises:
        AssertionError: If deviation exceeds `tol`, meaning the permutation
            algebra above is wrong.
    """
    a, b = forward(base, x), forward(permuted, x)
    denom = max(float(np.abs(a).max()), 1e-8)
    dev = float(np.abs(a - b).max() / denom)
    assert dev <= tol, (
        f"permuted model is NOT functionally equivalent to its base "
        f"(max relative deviation {dev:.3e} > tol {tol:.3e}). "
        f"The permutation algebra is wrong -- fix it before trusting any fixture."
    )
    return dev


# --------------------------------------------------------------------------- #
# config.json
# --------------------------------------------------------------------------- #


def mlp_config(spec: MLPSpec) -> dict[str, Any]:
    """Emit a HuggingFace-shaped config for an MLP.

    Intentionally describes the *architecture*, not our permutation groups. The
    topology resolver has to derive groups from this, which is the job it will
    have to do against the real evaluation fixtures.
    """
    return {
        "model_type": "synapse_mlp",
        "architectures": ["SynapseMLPForClassification"],
        "input_size": spec.in_dim,
        "hidden_size": spec.hidden,
        "num_hidden_layers": spec.depth,
        "num_labels": spec.out_dim,
        "hidden_act": "relu",
        "norm_type": "layer_norm",
        "layer_norm_eps": 1e-5,
        "torch_dtype": "float16",
    }


def cnn_config(spec: CNNSpec) -> dict[str, Any]:
    """Emit a HuggingFace-shaped config for a ResNet-style CNN."""
    return {
        "model_type": "synapse_resnet",
        "architectures": ["SynapseResNetForImageClassification"],
        "num_channels": spec.in_ch,
        "hidden_sizes": [spec.channels] * spec.blocks,
        "depths": [spec.blocks],
        "num_blocks": spec.blocks,
        "kernel_size": 3,
        "stride": 1,
        "padding": 1,
        "image_size": spec.spatial,
        "num_labels": spec.num_classes,
        "hidden_act": "relu",
        "norm_type": "batch_norm",
        "pooling": spec.head,
        "torch_dtype": "float16",
    }


# --------------------------------------------------------------------------- #
# Fixture assembly
# --------------------------------------------------------------------------- #


@dataclass
class Variant:
    """One generated model directory, ready to be written."""

    name: str
    tensors: Tensors
    groups: PermGroups | None = None
    provenance: dict[str, Any] = field(default_factory=dict)


def _write_variant(
    out_dir: Path, v: Variant, config: dict[str, Any], dtype: str
) -> dict[str, Any]:
    """Write one variant directory and return a manifest entry describing it."""
    d = out_dir / v.name
    d.mkdir(parents=True, exist_ok=True)

    storage: Tensors = {}
    overrides: dict[str, str] = {}
    for k, arr in v.tensors.items():
        conv, declared = to_storage_dtype(arr, dtype)
        storage[k] = conv
        if declared:
            overrides[k] = declared

    model_path = d / "model.safetensors"
    save_safetensors(
        model_path,
        storage,
        metadata={"format": "pt", "synapsefs_variant": v.name},
        dtype_overrides=overrides,
    )
    (d / "config.json").write_text(json.dumps(config, indent=2) + "\n")

    if v.groups is not None:
        # Written to its OWN file, never into config.json. The aligner reads
        # config.json; only tests may read this.
        (d / "ground_truth.json").write_text(
            json.dumps(
                {
                    "_warning": (
                        "Answer key. Tests and scoring only. "
                        "The alignment engine must never read this file."
                    ),
                    "permutations": {k: p.tolist() for k, p in v.groups.items()},
                    **v.provenance,
                },
                indent=2,
            )
            + "\n"
        )

    return {
        "variant": v.name,
        "path": str(d.relative_to(out_dir.parent)),
        "bytes": model_path.stat().st_size,
        "tensors": len(storage),
        "has_ground_truth": v.groups is not None,
        **v.provenance,
    }


def generate(
    arch: str,
    spec: MLPSpec | CNNSpec,
    out_dir: Path,
    seed: int,
    dtype: str,
    variants: Iterable[str],
    rel_scale: float,
    verify: bool = True,
) -> dict[str, Any]:
    """Generate one complete fixture set.

    Args:
        arch: ``"mlp"`` or ``"cnn"``.
        spec: The matching spec dataclass.
        out_dir: Directory to create; one subdirectory per variant.
        seed: Master seed. Everything downstream derives from it, so the whole
            set is reproducible from ``(arch, spec, seed)`` alone -- which is
            what lets us keep fixtures out of git.
        dtype: ``"fp16"``, ``"bf16"`` or ``"fp32"``.
        variants: Subset of :data:`ALL_VARIANTS` to emit.
        rel_scale: Fine-tuning noise scale, relative to each tensor's own std.
        verify: Run the functional-equivalence check on permuted variants.

    Returns:
        A manifest dict, also written to ``MANIFEST.json``.
    """
    wanted = list(variants)
    rng = np.random.default_rng(seed)

    if arch == "mlp":
        assert isinstance(spec, MLPSpec)
        base = build_mlp(spec, rng)
        config = mlp_config(spec)
        permute = lambda t, r: permute_mlp(spec, t, r)          # noqa: E731
        fwd = lambda t, x: forward_mlp(spec, t, x)              # noqa: E731
        probe = rng.normal(size=(4, spec.in_dim)).astype(np.float32)
        reinit = lambda r: build_mlp(spec, r)                   # noqa: E731
    elif arch == "cnn":
        assert isinstance(spec, CNNSpec)
        base = build_cnn(spec, rng)
        config = cnn_config(spec)
        permute = lambda t, r: permute_cnn(spec, t, r)          # noqa: E731
        fwd = lambda t, x: forward_cnn(spec, t, x)              # noqa: E731
        probe = rng.normal(size=(2, spec.in_ch, spec.spatial, spec.spatial)).astype(np.float32)
        reinit = lambda r: build_cnn(spec, r)                   # noqa: E731
    else:
        raise ValueError(f"unknown arch: {arch!r}")

    built: list[Variant] = []
    checks: dict[str, float] = {}

    if "base" in wanted:
        built.append(Variant("base", base, provenance={"derived_from": None}))

    perm_t: Tensors | None = None
    perm_g: PermGroups | None = None
    if {"permuted", "permuted_finetuned"} & set(wanted):
        perm_t, perm_g = permute(base, np.random.default_rng(seed + 1))
        if verify:
            checks["permuted"] = verify_equivalence(fwd, base, perm_t, probe)

    if "permuted" in wanted:
        built.append(
            Variant("permuted", perm_t, perm_g, {"derived_from": "base", "permuted": True})
        )

    if "finetuned" in wanted:
        built.append(
            Variant(
                "finetuned",
                finetune(base, np.random.default_rng(seed + 2), rel_scale),
                provenance={"derived_from": "base", "finetune_rel_scale": rel_scale},
            )
        )

    if "permuted_finetuned" in wanted:
        built.append(
            Variant(
                "permuted_finetuned",
                finetune(perm_t, np.random.default_rng(seed + 3), rel_scale),
                perm_g,
                {
                    "derived_from": "base",
                    "permuted": True,
                    "finetune_rel_scale": rel_scale,
                },
            )
        )

    if "not_alignable" in wanted:
        # Same architecture, independently initialised. Weight matching will
        # still *find* a permutation -- it always does -- but the residual will
        # barely improve over the unaligned baseline. That gap is the signal the
        # engine must detect and report, per the PS requirement to recognise
        # non-alignable pairs rather than force a low-confidence match.
        built.append(
            Variant(
                "not_alignable",
                reinit(np.random.default_rng(seed + 9999)),
                provenance={"derived_from": None, "independently_initialised": True},
            )
        )

    out_dir.mkdir(parents=True, exist_ok=True)
    entries = [_write_variant(out_dir, v, config, dtype) for v in built]

    manifest = {
        "arch": arch,
        "spec": spec.__dict__,
        "seed": seed,
        "dtype": dtype,
        "approx_params": spec.param_count,
        "regenerate_with": (
            f"python tools/gen_fixtures.py --arch {arch} --seed {seed} "
            f"--dtype {dtype} --out {out_dir}"
        ),
        "equivalence_max_rel_deviation": checks,
        "variants": entries,
    }
    if isinstance(spec, CNNSpec):
        manifest["col_block_size"] = spec.block_size

    (out_dir / "MANIFEST.json").write_text(json.dumps(manifest, indent=2) + "\n")
    return manifest


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #


def _human(n: int) -> str:
    """Format a byte count for progress output."""
    for unit in ("B", "KiB", "MiB", "GiB"):
        if n < 1024 or unit == "GiB":
            return f"{n:.1f} {unit}" if unit != "B" else f"{n} B"
        n /= 1024.0
    return f"{n:.1f} GiB"


def _check_disk(out: Path, spec: MLPSpec | CNNSpec, n_variants: int, dtype: str) -> None:
    """Warn before filling a nearly-full disk.

    The development machine has ~24 GB free on a 93%-full drive (docs/PLAN.md
    section 0), so a careless ``--size large --all`` is a real hazard.
    """
    per_elem = 4 if dtype == "fp32" else 2
    need = spec.param_count * per_elem * n_variants
    free = shutil.disk_usage(out.parent if out.parent.exists() else Path(".")).free
    print(f"  estimated output: {_human(need)}   free: {_human(free)}", file=sys.stderr)
    if need > free * 0.5:
        print(
            f"  WARNING: this would use more than half the free space on this "
            f"disk. Consider a smaller --size or fewer --variants.",
            file=sys.stderr,
        )


def main(argv: list[str] | None = None) -> int:
    """Entry point. Returns a process exit code."""
    ap = argparse.ArgumentParser(
        description="Generate synthetic SynapseFS checkpoint fixtures.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__.split("Usage\n-----\n")[-1],
    )
    ap.add_argument("--arch", choices=("mlp", "cnn"), help="architecture to generate")
    ap.add_argument("--all", action="store_true", help="generate both architectures")
    ap.add_argument("--size", choices=tuple(SIZE_PRESETS), default="tiny")
    ap.add_argument("--out", type=Path, required=True, help="output directory")
    ap.add_argument("--seed", type=int, default=0, help="master seed (default: 0)")
    ap.add_argument("--dtype", choices=("fp16", "bf16", "fp32"), default="fp16")
    ap.add_argument(
        "--variants",
        nargs="+",
        choices=ALL_VARIANTS,
        default=list(ALL_VARIANTS),
        help="subset of variants to emit (default: all five)",
    )
    ap.add_argument(
        "--finetune-scale",
        type=float,
        default=1e-3,
        help="fine-tuning noise, relative to each tensor's std (default: 1e-3)",
    )
    ap.add_argument(
        "--no-verify",
        action="store_true",
        help="skip the functional-equivalence check (not recommended)",
    )
    args = ap.parse_args(argv)

    if not args.arch and not args.all:
        ap.error("specify --arch {mlp,cnn} or --all")

    archs = ("mlp", "cnn") if args.all else (args.arch,)
    rc = 0

    for arch in archs:
        spec = SIZE_PRESETS[args.size][arch]
        out = args.out / f"{arch}-{args.size}" if args.all else args.out
        print(f"\n{arch} / {args.size}  (~{spec.param_count / 1e6:.1f}M params)", file=sys.stderr)
        _check_disk(out, spec, len(args.variants), args.dtype)

        try:
            m = generate(
                arch=arch,
                spec=spec,
                out_dir=out,
                seed=args.seed,
                dtype=args.dtype,
                variants=args.variants,
                rel_scale=args.finetune_scale,
                verify=not args.no_verify,
            )
        except AssertionError as e:
            print(f"  FAILED: {e}", file=sys.stderr)
            rc = 1
            continue

        for dev_name, dev in m["equivalence_max_rel_deviation"].items():
            print(f"  equivalence check [{dev_name}]: max rel dev {dev:.2e}  OK", file=sys.stderr)
        for e in m["variants"]:
            gt = "  + ground_truth.json" if e["has_ground_truth"] else ""
            print(f"  {e['variant']:<20} {_human(e['bytes']):>10}{gt}", file=sys.stderr)
        print(f"  manifest: {out / 'MANIFEST.json'}", file=sys.stderr)

    return rc


if __name__ == "__main__":
    raise SystemExit(main())
